name: Deploy Docs

on:
  push:
    branches: [master]
    paths:
      - 'README.md'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Create docs directory
        run: |
          mkdir -p _site
          cp README.md _site/
          echo '# sftui Documentation' > _site/index.md
          echo '' >> _site/index.md
          echo 'See [README.md](README.md) for full documentation.' >> _site/index.md
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4